server:
  port: 8080

wht:
  back:
    startGraphCompute: true
    mockDatabase: true #false/true
    domain: www.wanghongtao.xyz
    qq: 1946066280
    endpoint: 114.116.9.68
    virtualMachine: 192.168.240.128
    wifiMachine: 192.168.240.128 #172.30.206.167
    salt: "salt_wht"
spring:
  profiles:
    active: data


