version: '3'
services:
  simple_rebac:
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - 8080:8080
    environment:
      - RUNNING_IN_DOCKER=true
  mongo:
    image: mongo:4.4.29
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 19460
    volumes:
      - /Users/wht/data/mongo/db:/data/db
  mysql:
    restart: always
    image: mysql:8.0.25
    platform: linux/amd64
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 19460
    volumes:
      - /usr/local/docker/mysql:/var/lib/mysql
